version: 2.1

orbs:
  go: circleci/go@1.3.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test

  deploy:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - run:
          name: Install flyctl
          command: curl -L https://fly.io/install.sh | sh
      - run:
          name: Deploy app to flyctl
          command: flyctl deploy

workflows:
  main:
    jobs:
      - build
      - deploy