version: 2.1

orbs:
  go: circleci/go@1.3.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test
      - setup_remote_docker
      - run:
          name: Install flyctl
          command: curl -L https://fly.io/install.sh | sh
      - run:
          name: Deploy app to flyctl
          command: /home/circleci/.fly/bin/flyctl deploy

  deploy:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - run:
          name: Install flyctl
          command: curl -L https://fly.io/install.sh | sh
      # - run:
      #     name: Set flyctl paths
      #     command: export FLYCTL_INSTALL="/home/circleci/.fly"
      # - run:
      #     name: Set flyctl path
      #     command: export PATH="$FLYCTL_INSTALL/bin:$PATH"
      - run:
          name: Deploy app to flyctl
          command: /home/circleci/.fly/bin/flyctl deploy

workflows:
  main:
    jobs:
      - build
      # - deploy